install:
    - npm install
script:
    - npm test
cache:
  directories:
    - "node_modules"
# specify language
language: node_js
node_js:
  - "8.9.4"
# configure which branches to run
branches:
  # whitelist
  only:
    - master
